name: Deploy Backend (ECS)

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - uses: aws-actions/amazon-ecr-login@v2

    - name: Build & Push Image (immutable)
      run: |
        IMAGE_BASE=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ vars.ECR_REPOSITORY }}
        IMAGE_TAG=${{ github.sha }}

        docker build -t $IMAGE_BASE:$IMAGE_TAG backend
        docker push $IMAGE_BASE:$IMAGE_TAG

    - name: Render new task definition
      id: render
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: infra/modules/ecs_fargate/task-definition.json
        container-name: backend
        image: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ vars.ECR_REPOSITORY }}:${{ github.sha }}

    - name: Deploy to ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        cluster: ${{ vars.ECS_CLUSTER }}
        service: ${{ vars.ECS_SERVICE }}
        task-definition: ${{ steps.render.outputs.task-definition }}
